### ISSUE TITLE
Broken Build!!! Syntax error.

### ISSUE THREAD

**Issue by Brian-Kun** [hackumass/hackumass-ios#2]
Unceclaed types `LoginLabelCell `and `ButtonCell` in `LogInView`

I'm running Xcode Version 8.3.1 seems to just be a syntax error!

![screen shot 2017-04-16 at 12 24 54 pm](https://cloud.githubusercontent.com/assets/13333333/25072570/da1c92e4-229f-11e7-963d-ecadbdc551bf.png)

**Comment by alexj2space7** [comment]
I had the same issue, make sure all the files are loaded into github

**Comment by alexj2space7** [comment]
xcode^^^
